version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:8080

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - LISTARR_DB_HOST=db
      - LISTARR_DB_PORT=5432
      - LISTARR_DB_USER=postgres
      - LISTARR_DB_PASSWORD=yourpassword
      - LISTARR_DB_NAME=yourdb
    volumes:
      - config:/app/config
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  config:
    driver: local
    driver_opts:
      type: none
      device: /config/listarr/temp_config
      o: bind
